# Uncomment the next line to define a global platform for your project
# platform :ios, '13.5'

target 'TrueLayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TLList', :path => '../TLList'

 end

# Workaround for Cocoapods issue #7606
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end

end
